### PR TITLE
Recipe APP - Final Review

### PR DESCRIPTION
**Pull request by raihan2bd**
# 🥘 Recipe APP 
Hi There 👋 ,
### In this branch, My partner @gaks1  and I made the following changes ⬇️ 

- [ ] We added `login` and` registration` pages using the `devise`
- [ ] After that added a `food` list where users can manage it.
- [ ] Added a `recipe` list where users can manage it and see a single recipe details page.
- [ ] Added features to make the recipe `public/private`, `Generate a shopping list`, and `Add ingredient`
- [ ]  Added a page to display all the `public recipes`
- [ ] Added a `navigation menu`
- [ ] Solved `n+1 queries`
- [ ] Added necessary `styles` to this project
- [ ] Added necessary `tests` for this application `including (Unit, Integration)`
- [ ] Fixed `linter errors` from the project

*`Note`: If you want to run the test make sure you create a user where the user email: `raihan1@gmail.com` and password: `123456`. or you can seed your database using the project `seeds file`*

***Thanks for visiting 👍. If you have any questions feel free to ask 🙂***

### CODE REVIEW

**Review by Lizdev-05 — CHANGES_REQUESTED** [review]
Hi @raihan2bd, @gaks1  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- *  Descriptive Pull Request message ✔️
- *  Good use of GitHub flow ✔️
- *  Meaningful commit messages ✔️
- *  No linter error ✔️
- *  Brilliant implementation ✔️

## Required Changes ♻️

- [ ]  Presently, I am unable to log in after signing up as the app kept asking me to confirm the email but no email confirmation was sent.
**These are the steps I have taken so far...**
- I registered with two different emails, but no confirmation mail was sent
- I made use of confirm email field, no email was sent
- I checked the terminal, no place to confirm the email
- Created another account with raihan1@gmail.com, but no way to login also

Kindly, work around this, so that authentication can be confirmable and the users will be able to access the page.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A
Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gaks1** [comment]
@Lizdev-05  did you check the terminal for it 
Screenshot 2023-06-30 200939
i am getting one on my side

**Comment by gaks1** [comment]
https://github.com/gaks1/recipe-app/assets/44966918/59c4d26b-a321-4c3c-9686-b4cec7c68939

**Review by victorokoroji — APPROVED** [review]
Hi @raihan2bd, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
